### ISSUE TITLE
Fix badly written entities

### ISSUE THREAD

**Issue by SamPujade** [ArianeDlns/chatbot-presidentielle2022#6]
Fix badly written entities with embedding/classification

### Actual

Input : 
`Quel est le parti de Melanchon ?`

Output:
`Je ne reconnais pas le nom de ce candidat. L'avez-vous bien écrit ?`

### Expected

Input : 
`Quel est le parti de Melanchon ?`

Output:
`Le parti de Jean-Luc Mélenchon est La France Insoumise.`

**Comment by ArianeDlns** [comment]
+1 - Same issue for polls data

**Comment by ArianeDlns** [comment]
Adding utils.candidate_names to fix this

**Comment by ArianeDlns** [comment]
Closing this issue - An improvement could be made to add and compare with known synonyms
